### ISSUE TITLE
Error when trying to run command on a MOV file outputted by Davinci Resolve

### ISSUE THREAD

**Issue by Tanza3D** [slhck/ffmpeg-black-split#3]
**:warning: Please read this carefully and edit the example responses! If you do not fill out this information, your bug report may be closed without comment.**

**Checklist** (please tick all boxes)
- [x] I am using the latest version of `ffmpeg-black-split` (run `pip3 install --upgrade ffmpeg-black-split`)
- [x] I am using the latest stable version of `ffmpeg` or a recent build from Git master

**Expected behavior**
It to work

**Actual behavior**
```
Traceback (most recent call last):
  File "/home/tanza/.local/bin/ffmpeg-black-split", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tanza/.local/lib/python3.12/site-packages/ffmpeg_black_split/__main__.py", line 114, in main
    ffbs.cut_all_periods(
  File "/home/tanza/.local/lib/python3.12/site-packages/ffmpeg_black_split/_black_split.py", line 222, in cut_all_periods
    self.cut_part_from_file(
  File "/home/tanza/.local/lib/python3.12/site-packages/ffmpeg_black_split/_black_split.py", line 331, in cut_part_from_file
    for _ in ff.run_command_with_progress():
  File "/home/tanza/.local/lib/python3.12/site-packages/ffmpeg_progress_yield/ffmpeg_progress_yield.py", line 261, in run_command_with_progress
    raise RuntimeError(f"Error running command {self.cmd}: {_pretty_stderr}")
RuntimeError: Error running command ['ffmpeg', '-hide_banner', '-y', '-ss', '0.0', '-i', 'Timeline_clean.mov', '-t', '198.875', '-c', 'copy', '-map', '0', '/home/tanza/Videos/Timeline_clean_0.0-198.875.mkv']: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Timeline_clean.mov':
Metadata:
major_brand     : qt
minor_version   : 512
compatible_brands: qt
encoder         : Lavf61.1.100
Duration: 00:34:10.08, start: 0.000000, bitrate: 3502 kb/s
Stream #0:0[0x1]: Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p(bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1195 kb/s, 24 fps, 24 tbr, 12288 tbn (default)
Metadata:
handler_name    : VideoHandler
vendor_id       : FFMP
encoder         : MPEG4 Video
timecode        : 01:00:00:00
Stream #0:1[0x2]: Audio: pcm_s24le (in24 / 0x34326E69), 48000 Hz, stereo, s32 (24 bit), 2304 kb/s (default)
Metadata:
handler_name    : SoundHandler
vendor_id       : [0][0][0][0]
Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74)
Metadata:
handler_name    : VideoHandler
timecode        : 01:00:00:00
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
[matroska @ 0x645d7c9bb9c0] Only audio, video, and subtitles are supported for Matroska.
[out#0/matroska @ 0x645d7c9bad40] Could not write header (incorrect codec parameters ?): Invalid argument
Conversion failed!
```

**Command**
The exact command you were trying to run:

```
ffmpeg-black-split Timeline_clean.mov
```

Any output you get when running the command with the `-v` flag:

```
nothing of importance
```

**Environment (please complete the following information):**
- [X] Your operating system
Manjaro Linux
- [X] Your Python version / distribution (`python3 --version` or `python --version`)
Python 3.12.4
- [X] Your ffmpeg version (`ffmpeg -version`)
```
ffmpeg version n7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 14.1.1 (GCC) 20240522
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-frei0r --enable-gmp --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-mbedtls --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-vapoursynth --enable-version3 --enable-vulkan
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```

This is the file I'm trying to split: https://music.untone.uk/promodl/dl/Timeline_clean.mov

**Comment by Tanza3D** [comment]
Telling ffmpeg to specifically map the audio and video with these arguments seems to work
"-map", "0:v", "-map", "0:a"

**Comment by slhck** [comment]
Thanks for the detailed report. The problem is that the `tmcd` data stream, which is specific to QuickTime/MOV files cannot be mapped to the output file:

> `[matroska @ 0x645d7c9bb9c0] Only audio, video, and subtitles are supported for Matroska.`

Your workaround solves the issue for that particular file. That said, if the input contains no audio, the command will fail. There is an alternative syntax to make this work (`-map -0:d`). Or one might choose another extension for the output.

I will add a safeguard for MKV files and allow selection of other extensions.

**Comment by slhck** [comment]
Please try with version v0.6.0 that I just released.
